CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  display_name VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','CHEF_FLICS') NOT NULL DEFAULT 'CHEF_FLICS',
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sessions (
  token_hash CHAR(64) NOT NULL PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX sessions_user_id_idx (user_id),
  INDEX sessions_expires_at_idx (expires_at),
  CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bleus (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Nom VARCHAR(255) NOT NULL,
  Prenom VARCHAR(255) NOT NULL,
  Sexe VARCHAR(255) NOT NULL DEFAULT '',
  DateN VARCHAR(255) NOT NULL DEFAULT '',
  Adresse TEXT NOT NULL,
  Med TEXT NOT NULL,
  Com TEXT NOT NULL,
  Tel VARCHAR(255) NOT NULL DEFAULT '',
  Regio VARCHAR(255) NOT NULL DEFAULT '',
  Supp TINYINT(1) NOT NULL DEFAULT 0,
  RespLegal TEXT NOT NULL,
  NumRespLegal VARCHAR(255) NOT NULL DEFAULT '',
  Ramassage1 TEXT NOT NULL,
  Ramassage2 TEXT NOT NULL,
  Ramassage3 TEXT NOT NULL,
  Ramassage4 TEXT NOT NULL,
  source ENUM('MANUAL','GOOGLE_FORM','LEGACY_IMPORT') NOT NULL DEFAULT 'MANUAL',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX bleus_nom_prenom_idx (Nom, Prenom),
  INDEX bleus_regio_idx (Regio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  bleu_id BIGINT UNSIGNED NULL,
  action VARCHAR(50) NOT NULL,
  details JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX audit_user_idx (user_id),
  INDEX audit_bleu_idx (bleu_id),
  CONSTRAINT audit_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT audit_bleu_fk FOREIGN KEY (bleu_id) REFERENCES bleus(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
